<?php
// Rotas REST para manipulação da tabela msg_001_timeline
// {{www}}/index.php/api/v1/msg-timeline/find
$routes->post('find', 'Api\V1\Msg\MessageTimeline\ResourceTableController::find');
// {{www}}/index.php/api/v1/msg-timeline/get-grouped
$routes->post('get-grouped', 'Api\V1\Msg\MessageTimeline\ResourceTableController::getGrouped');
// {{www}}/index.php/api/v1/msg-timeline/search
$routes->get('search', 'Api\V1\Msg\MessageTimeline\ResourceTableController::search');
// {{www}}/index.php/api/v1/msg-timeline/get/{id}
$routes->get('get/(:num)', 'Api\V1\Msg\MessageTimeline\ResourceTableController::get/$1');
// {{www}}/index.php/api/v1/msg-timeline/get-all
$routes->get('get-all', 'Api\V1\Msg\MessageTimeline\ResourceTableController::getAll');
// {{www}}/index.php/api/v1/msg-timeline/get-no-pagination
$routes->get('get-no-pagination', 'Api\V1\Msg\MessageTimeline\ResourceTableController::getNoPagination');
// {{www}}/index.php/api/v1/msg-timeline/get-deleted/{id}
$routes->get('get-deleted/(:num)', 'Api\V1\Msg\MessageTimeline\ResourceTableController::getDeleted/$1');
// {{www}}/index.php/api/v1/msg-timeline/get-all-with-deleted/{id}
$routes->get('get-all-with-deleted/(:num)', 'Api\V1\Msg\MessageTimeline\ResourceTableController::getAllWithDeleted/$1');
// {{www}}/index.php/api/v1/msg-timeline/get-all-with-deleted
$routes->get('get-all-with-deleted', 'Api\V1\Msg\MessageTimeline\ResourceTableController::getAllWithDeleted');
// {{www}}/index.php/api/v1/msg-timeline/get-deleted-all
$routes->get('get-deleted-all', 'Api\V1\Msg\MessageTimeline\ResourceTableController::getDeletedAll');
// {{www}}/index.php/api/v1/msg-timeline/get-with-deleted/{id}
$routes->get('get-with-deleted/(:num)', 'Api\V1\Msg\MessageTimeline\ResourceTableController::getWithDeleted/$1');
// {{www}}/index.php/api/v1/msg-timeline/create
$routes->post('create', 'Api\V1\Msg\MessageTimeline\ResourceTableController::create');
// {{www}}/index.php/api/v1/msg-timeline/update/{id}
$routes->put('update/(:num)', 'Api\V1\Msg\MessageTimeline\ResourceTableController::update/$1');
// {{www}}/index.php/api/v1/msg-timeline/delete-soft/{id}
$routes->delete('delete-soft/(:num)', 'Api\V1\Msg\MessageTimeline\ResourceTableController::deleteSoft/$1');
// {{www}}/index.php/api/v1/msg-timeline/delete-restore/{id}
$routes->patch('delete-restore/(:num)', 'Api\V1\Msg\MessageTimeline\ResourceTableController::deleteRestore/$1');
// {{www}}/index.php/api/v1/msg-timeline/delete-hard/{id}
$routes->delete('delete-hard/(:num)', 'Api\V1\Msg\MessageTimeline\ResourceTableController::deleteHard/$1');
// {{www}}/index.php/api/v1/msg-timeline/clear-deleted
$routes->delete('clear-deleted', 'Api\V1\Msg\MessageTimeline\ResourceTableController::clearDeleted');
// {{www}}/index.php/api/v1/msg-timeline/clear-deleted/{id}
$routes->delete('clear-deleted/(:num)', 'Api\V1\Msg\MessageTimeline\ResourceTableController::clearDeleted/$1');
// {{www}}/index.php/api/v1/msg-timeline/debug-request  [TEMPORÁRIO — remover após diagnóstico]
$routes->post('debug-request', 'Api\V1\Msg\MessageTimeline\ResourceTableController::debugRequest');
// {{www}}/index.php/api/v1/msg-timeline/upload-files/{userCustomerId}
$routes->post('upload-files/(:num)', 'Api\V1\Msg\MessageTimeline\ResourceTableController::uploadAttachments/$1');
