import type { GlobalTheme } from './types'

const themeLight: GlobalTheme = {
  name: 'Light',
  login: {
    bgStart:     '#E8EAF6',
    bgMid:       '#C5CAE9',
    bgEnd:       '#9FA8DA',
    cardBg:      '#FFFFFF',
    headerStart: '#5C6BC0',
    headerEnd:   '#3949AB',
    headerText:  '#FFFFFF',
    btnBg:       '#3949AB',
    btnBgHover:  '#00BFFF',
    btnText:     '#FFFFFF',
    link:        '#3949AB',
    linkHover:   '#00BFFF',
  },
  colors: {
    bg:            '#f8f9fa',
    surface:       '#ffffff',
    primary:       '#3949AB',
    primaryText:   '#ffffff',
    text:          '#212529',
    textMuted:     '#6c757d',
    border:        '#dee2e6',
    divider:       '#f1f3f5',
    inputBg:       '#ffffff',
    inputBorder:   '#dee2e6',
    inputText:     '#212529',
    placeholder:   '#6c757d',
    success:       '#198754',
    successBg:     '#d1e7dd',
    successBorder: '#a3cfbb',
    successText:   '#0a3622',
    danger:        '#dc3545',
    dangerBg:      '#f8d7da',
    dangerBorder:  '#f5c2c7',
    dangerText:    '#842029',
    warningBg:     '#fff3cd',
    warningBorder: '#ffc107',
    warningText:   '#856404',
  },
}

export default themeLight
