import type { GlobalTheme } from './types'

const themePurple: GlobalTheme = {
  name: 'Purple',
  login: {
    bgStart:     '#1A1A2E',
    bgMid:       '#4A3F6B',
    bgEnd:       '#663399',
    cardBg:      '#FFFFFF',
    headerStart: '#4A3F6B',
    headerEnd:   '#8A2BE2',
    headerText:  '#FFFFFF',
    btnBg:       '#8A2BE2',
    btnBgHover:  '#7122C5',
    btnText:     '#FFFFFF',
    link:        '#8A2BE2',
    linkHover:   '#BA55D3',
  },
  colors: {
    bg:            '#1A1A2E',
    surface:       '#242448',
    primary:       '#8A2BE2',
    primaryText:   '#FFFFFF',
    text:          '#E0D8F8',
    textMuted:     '#B0A0D0',
    border:        '#3A3060',
    divider:       '#2A2048',
    inputBg:       '#1E1E40',
    inputBorder:   '#4A3F6B',
    inputText:     '#E0D8F8',
    placeholder:   '#8A7AAA',
    success:       '#66BB6A',
    successBg:     '#1A2E1D',
    successBorder: '#2A4A30',
    successText:   '#A5D6A7',
    danger:        '#EF5350',
    dangerBg:      '#2E1418',
    dangerBorder:  '#4A2028',
    dangerText:    '#FFCDD2',
    warningBg:     '#2E2614',
    warningBorder: '#FFB300',
    warningText:   '#FFD54F',
  },
}

export default themePurple
