import type { GlobalTheme } from './types'

const themePurple: GlobalTheme = {
  name: 'Purple',
  login: {
    bgStart:     '#2A1550',
    bgMid:       '#5B2D8E',
    bgEnd:       '#8B5CF6',
    cardBg:      '#FFFFFF',
    headerStart: '#5B2D8E',
    headerEnd:   '#A855F7',
    headerText:  '#FFFFFF',
    btnBg:       '#A855F7',
    btnBgHover:  '#9333EA',
    btnText:     '#FFFFFF',
    link:        '#A855F7',
    linkHover:   '#C084FC',
  },
  colors: {
    bg:            '#2A1550',
    surface:       '#3D2070',
    primary:       '#A855F7',
    primaryText:   '#FFFFFF',
    text:          '#F0E6FF',
    textMuted:     '#C4A0E8',
    border:        '#6644AA',
    divider:       '#3A1E60',
    inputBg:       '#321860',
    inputBorder:   '#7755CC',
    inputText:     '#F0E6FF',
    placeholder:   '#9977CC',
    success:       '#66BB6A',
    successBg:     '#1A2E1D',
    successBorder: '#2A4A30',
    successText:   '#A5D6A7',
    danger:        '#EF5350',
    dangerBg:      '#2E1418',
    dangerBorder:  '#4A2028',
    dangerText:    '#FFCDD2',
    warningBg:     '#2E2614',
    warningBorder: '#FFB300',
    warningText:   '#FFD54F',
  },
}

export default themePurple
