<?php
// Rotas REST para manipulação da tabela user_management
// {{www}}/index.php/api/v1/user-management/find
$routes->post('find', 'Api\V1\UserManagement\ResourceTableController::find');
// {{www}}/index.php/api/v1/user-management/get-grouped
$routes->post('get-grouped', 'Api\V1\UserManagement\ResourceTableController::getGrouped');
// {{www}}/index.php/api/v1/user-management/search
$routes->get('search', 'Api\V1\UserManagement\ResourceTableController::search');
// {{www}}/index.php/api/v1/user-management/get/{id}
$routes->get('get/(:num)', 'Api\V1\UserManagement\ResourceTableController::get/$1');
// {{www}}/index.php/api/v1/user-management/get-all
$routes->get('get-all', 'Api\V1\UserManagement\ResourceTableController::getAll');
// {{www}}/index.php/api/v1/user-management/get-no-pagination
$routes->get('get-no-pagination', 'Api\V1\UserManagement\ResourceTableController::getNoPagination');
// {{www}}/index.php/api/v1/user-management/get-deleted/{id}
$routes->get('get-deleted/(:num)', 'Api\V1\UserManagement\ResourceTableController::getDeleted/$1');
// {{www}}/index.php/api/v1/user-management/get-deleted-all
$routes->get('get-deleted-all', 'Api\V1\UserManagement\ResourceTableController::getDeletedAll');
// {{www}}/index.php/api/v1/user-management/create
$routes->post('create', 'Api\V1\UserManagement\ResourceTableController::create');
// {{www}}/index.php/api/v1/user-management/update/{id}
$routes->put('update/(:num)', 'Api\V1\UserManagement\ResourceTableController::update/$1');
// {{www}}/index.php/api/v1/user-management/delete-soft/{id}
$routes->delete('delete-soft/(:num)', 'Api\V1\UserManagement\ResourceTableController::deleteSoft/$1');
// {{www}}/index.php/api/v1/user-management/delete-restore/{id}
$routes->patch('delete-restore/(:num)', 'Api\V1\UserManagement\ResourceTableController::deleteRestore/$1');
// {{www}}/index.php/api/v1/user-management/delete-hard/{id}
$routes->delete('delete-hard/(:num)', 'Api\V1\UserManagement\ResourceTableController::deleteHard/$1');
// {{www}}/index.php/api/v1/user-management/clear-deleted
$routes->delete('clear-deleted', 'Api\V1\UserManagement\ResourceTableController::clearDeleted');
// {{www}}/index.php/api/v1/user-management/clear-deleted/{id}
$routes->delete('clear-deleted/(:num)', 'Api\V1\UserManagement\ResourceTableController::clearDeleted/$1');
