<?php
// Rotas REST para manipulação da tabela msg_005_group_member
// {{www}}/index.php/api/v1/msg/group-member/find
$routes->post('find', 'Api\V1\Msg\GroupMember\ResourceTableController::find');
// {{www}}/index.php/api/v1/msg/group-member/get-grouped
$routes->post('get-grouped', 'Api\V1\Msg\GroupMember\ResourceTableController::getGrouped');
// {{www}}/index.php/api/v1/msg/group-member/search
$routes->get('search', 'Api\V1\Msg\GroupMember\ResourceTableController::search');
// {{www}}/index.php/api/v1/msg/group-member/get/{id}
$routes->get('get/(:num)', 'Api\V1\Msg\GroupMember\ResourceTableController::get/$1');
// {{www}}/index.php/api/v1/msg/group-member/get-all
$routes->get('get-all', 'Api\V1\Msg\GroupMember\ResourceTableController::getAll');
// {{www}}/index.php/api/v1/msg/group-member/get-no-pagination
$routes->get('get-no-pagination', 'Api\V1\Msg\GroupMember\ResourceTableController::getNoPagination');
// {{www}}/index.php/api/v1/msg/group-member/get-deleted/{id}
$routes->get('get-deleted/(:num)', 'Api\V1\Msg\GroupMember\ResourceTableController::getDeleted/$1');
// {{www}}/index.php/api/v1/msg/group-member/get-deleted-all
$routes->get('get-deleted-all', 'Api\V1\Msg\GroupMember\ResourceTableController::getDeletedAll');
// {{www}}/index.php/api/v1/msg/group-member/get-with-deleted/{id}
$routes->get('get-with-deleted/(:num)', 'Api\V1\Msg\GroupMember\ResourceTableController::getWithDeleted/$1');
// {{www}}/index.php/api/v1/msg/group-member/create
$routes->post('create', 'Api\V1\Msg\GroupMember\ResourceTableController::create');
// {{www}}/index.php/api/v1/msg/group-member/update/{id}
$routes->put('update/(:num)', 'Api\V1\Msg\GroupMember\ResourceTableController::update/$1');
// {{www}}/index.php/api/v1/msg/group-member/delete-soft/{id}
$routes->delete('delete-soft/(:num)', 'Api\V1\Msg\GroupMember\ResourceTableController::deleteSoft/$1');
// {{www}}/index.php/api/v1/msg/group-member/delete-restore/{id}
$routes->patch('delete-restore/(:num)', 'Api\V1\Msg\GroupMember\ResourceTableController::deleteRestore/$1');
// {{www}}/index.php/api/v1/msg/group-member/delete-hard/{id}
$routes->delete('delete-hard/(:num)', 'Api\V1\Msg\GroupMember\ResourceTableController::deleteHard/$1');
// {{www}}/index.php/api/v1/msg/group-member/clear-deleted
$routes->delete('clear-deleted', 'Api\V1\Msg\GroupMember\ResourceTableController::clearDeleted');
// {{www}}/index.php/api/v1/msg/group-member/clear-deleted/{id}
$routes->delete('clear-deleted/(:num)', 'Api\V1\Msg\GroupMember\ResourceTableController::clearDeleted/$1');
