<?php
// Rotas REST para manipulação da tabela msg_002_timeline_reaction
// {{www}}/index.php/api/v1/msg/timeline-reaction/find
$routes->post('find', 'Api\V1\Msg\TimelineReaction\ResourceTableController::find');
// {{www}}/index.php/api/v1/msg/timeline-reaction/get-grouped
$routes->post('get-grouped', 'Api\V1\Msg\TimelineReaction\ResourceTableController::getGrouped');
// {{www}}/index.php/api/v1/msg/timeline-reaction/search
$routes->get('search', 'Api\V1\Msg\TimelineReaction\ResourceTableController::search');
// {{www}}/index.php/api/v1/msg/timeline-reaction/get/{id}
$routes->get('get/(:num)', 'Api\V1\Msg\TimelineReaction\ResourceTableController::get/$1');
// {{www}}/index.php/api/v1/msg/timeline-reaction/get-all
$routes->get('get-all', 'Api\V1\Msg\TimelineReaction\ResourceTableController::getAll');
// {{www}}/index.php/api/v1/msg/timeline-reaction/get-no-pagination
$routes->get('get-no-pagination', 'Api\V1\Msg\TimelineReaction\ResourceTableController::getNoPagination');
// {{www}}/index.php/api/v1/msg/timeline-reaction/get-deleted/{id}
$routes->get('get-deleted/(:num)', 'Api\V1\Msg\TimelineReaction\ResourceTableController::getDeleted/$1');
// {{www}}/index.php/api/v1/msg/timeline-reaction/get-deleted-all
$routes->get('get-deleted-all', 'Api\V1\Msg\TimelineReaction\ResourceTableController::getDeletedAll');
// {{www}}/index.php/api/v1/msg/timeline-reaction/get-with-deleted/{id}
$routes->get('get-with-deleted/(:num)', 'Api\V1\Msg\TimelineReaction\ResourceTableController::getWithDeleted/$1');
// {{www}}/index.php/api/v1/msg/timeline-reaction/create
$routes->post('create', 'Api\V1\Msg\TimelineReaction\ResourceTableController::create');
// {{www}}/index.php/api/v1/msg/timeline-reaction/update/{id}
$routes->put('update/(:num)', 'Api\V1\Msg\TimelineReaction\ResourceTableController::update/$1');
// {{www}}/index.php/api/v1/msg/timeline-reaction/delete-soft/{id}
$routes->delete('delete-soft/(:num)', 'Api\V1\Msg\TimelineReaction\ResourceTableController::deleteSoft/$1');
// {{www}}/index.php/api/v1/msg/timeline-reaction/delete-restore/{id}
$routes->patch('delete-restore/(:num)', 'Api\V1\Msg\TimelineReaction\ResourceTableController::deleteRestore/$1');
// {{www}}/index.php/api/v1/msg/timeline-reaction/delete-hard/{id}
$routes->delete('delete-hard/(:num)', 'Api\V1\Msg\TimelineReaction\ResourceTableController::deleteHard/$1');
// {{www}}/index.php/api/v1/msg/timeline-reaction/clear-deleted
$routes->delete('clear-deleted', 'Api\V1\Msg\TimelineReaction\ResourceTableController::clearDeleted');
// {{www}}/index.php/api/v1/msg/timeline-reaction/clear-deleted/{id}
$routes->delete('clear-deleted/(:num)', 'Api\V1\Msg\TimelineReaction\ResourceTableController::clearDeleted/$1');
