<?php
// Rotas REST para manipulação da tabela user_004_saas_tenants
// {{www}}/index.php/api/v1/user-saas-tenants/find
$routes->post('find', 'Api\V1\User\UserSaasTenants\ResourceTableController::find');
// {{www}}/index.php/api/v1/user-saas-tenants/get-grouped
$routes->post('get-grouped', 'Api\V1\User\UserSaasTenants\ResourceTableController::getGrouped');
// {{www}}/index.php/api/v1/user-saas-tenants/search
$routes->get('search', 'Api\V1\User\UserSaasTenants\ResourceTableController::search');
// {{www}}/index.php/api/v1/user-saas-tenants/get/{id}
$routes->get('get/(:num)', 'Api\V1\User\UserSaasTenants\ResourceTableController::get/$1');
// {{www}}/index.php/api/v1/user-saas-tenants/get-all
$routes->get('get-all', 'Api\V1\User\UserSaasTenants\ResourceTableController::getAll');
// {{www}}/index.php/api/v1/user-saas-tenants/get-no-pagination
$routes->get('get-no-pagination', 'Api\V1\User\UserSaasTenants\ResourceTableController::getNoPagination');
// {{www}}/index.php/api/v1/user-saas-tenants/get-deleted/{id}
$routes->get('get-deleted/(:num)', 'Api\V1\User\UserSaasTenants\ResourceTableController::getDeleted/$1');
// {{www}}/index.php/api/v1/user-saas-tenants/get-all-with-deleted/{id}
$routes->get('get-all-with-deleted/(:num)', 'Api\V1\User\UserSaasTenants\ResourceTableController::getAllWithDeleted/$1');
// {{www}}/index.php/api/v1/user-saas-tenants/get-all-with-deleted
$routes->get('get-all-with-deleted', 'Api\V1\User\UserSaasTenants\ResourceTableController::getAllWithDeleted');
// {{www}}/index.php/api/v1/user-saas-tenants/get-deleted-all
$routes->get('get-deleted-all', 'Api\V1\User\UserSaasTenants\ResourceTableController::getDeletedAll');
// {{www}}/index.php/api/v1/user-saas-tenants/get-with-deleted/{id}
$routes->get('get-with-deleted/(:num)', 'Api\V1\User\UserSaasTenants\ResourceTableController::getWithDeleted/$1');
// {{www}}/index.php/api/v1/user-saas-tenants/create
$routes->post('create', 'Api\V1\User\UserSaasTenants\ResourceTableController::create');
// {{www}}/index.php/api/v1/user-saas-tenants/update/{id}
$routes->put('update/(:num)', 'Api\V1\User\UserSaasTenants\ResourceTableController::update/$1');
// {{www}}/index.php/api/v1/user-saas-tenants/delete-soft/{id}
$routes->delete('delete-soft/(:num)', 'Api\V1\User\UserSaasTenants\ResourceTableController::deleteSoft/$1');
// {{www}}/index.php/api/v1/user-saas-tenants/delete-restore/{id}
$routes->patch('delete-restore/(:num)', 'Api\V1\User\UserSaasTenants\ResourceTableController::deleteRestore/$1');
// {{www}}/index.php/api/v1/user-saas-tenants/delete-hard/{id}
$routes->delete('delete-hard/(:num)', 'Api\V1\User\UserSaasTenants\ResourceTableController::deleteHard/$1');
// {{www}}/index.php/api/v1/user-saas-tenants/clear-deleted
$routes->delete('clear-deleted', 'Api\V1\User\UserSaasTenants\ResourceTableController::clearDeleted');
// {{www}}/index.php/api/v1/user-saas-tenants/clear-deleted/{id}
$routes->delete('clear-deleted/(:num)', 'Api\V1\User\UserSaasTenants\ResourceTableController::clearDeleted/$1');
